### ISSUE TITLE
Do not show Maven and Gradle steps to running Python recipes for now

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-recipe-markdown-generator#105]
Right now the docs for Python recipes also show Maven and Gradle tabs
https://docs.openrewrite.org/recipes/python/changemethodname

![image](https://github.com/openrewrite/rewrite-recipe-markdown-generator/assets/1027334/58bf68f7-6b00-4a49-9ac4-778e14aa15bb)

In reality these recipes can only be run through the Moderne CLI for now, as we [took out the parser](https://github.com/openrewrite/rewrite-maven-plugin/commit/0ad0666ebf2451bc27b05b1dbe24596f6b166aee) a while ago.

We should update the doc generator to take out those run instructions for Maven and Gradle, and only keep the Moderne CLI as an option.

**Comment by okundzich** [comment]
I don't think we should be publishing anything for python at the moment. more work is needed.

**Comment by mike-solomon** [comment]
Removed Python from the generated docs here: https://github.com/openrewrite/rewrite-recipe-markdown-generator/commit/b231676a511ed6446a2706fe48e1bf6b03f779da

I'm fine keeping this issue around for if/when we add it back for context. Feel free to close if you'd like, though @timtebeek .

**Comment by timtebeek** [comment]
Thanks for those quick changes! I'm fine keeping this issue closed. We can always revisit in the future, and would be quick enough to realize that this change is then necessary.
