### ISSUE TITLE
Sort recipe catalog

### ISSUE THREAD

**Issue by mike-solomon** [openrewrite/rewrite-recipe-markdown-generator#117]
I'm not entirely sure how the recipe catalog is sorted right now - but it's definitely not alphabetically. If possible, we should sort so that's it clearer what recipes exist.

![image](https://github.com/openrewrite/rewrite-recipe-markdown-generator/assets/1187834/acd875e7-6410-45b0-9c86-d10cc191069b)

**Comment by okundzich** [comment]
in the SaaS I believe we sort by number of recipes included, so the categories with the most recipes are surfaced first.
