### ISSUE TITLE
Sort the recipe menu alphabetically (or at least the main categories)

### ISSUE THREAD

**Issue by Philzen** [openrewrite/rewrite-recipe-markdown-generator#119]
## What problem are you trying to solve?

I was just looking at the description of "AssertJByteRules Refaster recipes". Then i wanted to look up something in the Java section … finding that section took me ages, because the menu looks like this:

![grafik](https://github.com/openrewrite/rewrite-docs/assets/1634615/655daa9e-790a-4091-b569-64c6972e3db0)

## Describe the solution you'd like

Maybe it's just me, but i'd argue it's a common expectation to find the Java category right above "Jenkins". But it is much further up, somewhere below "Search" and above "Analysis" :see_no_evil: 

![grafik](https://github.com/openrewrite/rewrite-docs/assets/1634615/74557c77-e85c-4543-b528-24e0ea2bd02f)

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

Yup.

**Comment by timtebeek** [comment]
Thanks for the suggestion! I'm not sure what order we use, but it _feels_ like we use the order of [how the recipe dependencies are declared](https://github.com/openrewrite/rewrite-recipe-markdown-generator/blob/208a9d193b6fbcc06e5bcec3b6a11b425b0e4bb5/build.gradle.kts#L60-L111). Might indeed make more sense to add a predictable ordering, especially with how much the catalog has grown.

Note that I moved the issue to the repository that parses the recipes and generates the docs. It's a bit of a unpolished script, but works  well enough up to now.

**Comment by mike-solomon** [comment]
I believe I've fixed this so the catalog is sorted alphabetically now. If you run into any issues with it - please let me know :D
