### ISSUE TITLE
Spring Recipe sub-category links are broken

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-recipe-markdown-generator#13]
![image](https://user-images.githubusercontent.com/22326988/189179996-f89d5384-9995-45b6-9f4c-79e29a907280.png)

https://docs.openrewrite.org/reference/recipes/java/spring

**Comment by timtebeek** [comment]
Might be more broadly applicable; any recipe link under https://docs.openrewrite.org/reference/recipes/java/migrate fails for me as well; subcategories work there, but recipe links do not redirect anywhere.

**Comment by tkvangorder** [comment]
We regenerated the recipe docs and I believe all links are working again (both in the spring sub-categories and migrate recipe links)

**Comment by timtebeek** [comment]
Works indeed; thanks! And nice to see the new tab show up: 
![image](https://user-images.githubusercontent.com/1027334/192329652-831b97ad-f8a6-4c93-8aea-6f47ab4c58c3.png)
