### ISSUE TITLE
Generate document of new recipes per release

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-recipe-markdown-generator#17]
We now have so many recipes it's easy not to notice when a new one is added.
To highlight new contributions, it would be helpful for this to generate a list of recipes new since the previous release. 
Could further be augmented with a slack integration which posts to the OSS community slack

**Comment by mike-solomon** [comment]
[This PR](https://github.com/openrewrite/rewrite-recipe-markdown-generator/pull/19) includes code for generating a YML file of all the recipes for a given release. A human could then look at the diff in GitHub to see what has changed.

This will speed up the process -- but isn't fully automated in the sense that a human will still need to look at the diff and post in Slack.

**Comment by mike-solomon** [comment]
This has been fixed. A changelog is now added whenever a new release is done. https://github.com/openrewrite/rewrite-recipe-markdown-generator/pull/27
