### ISSUE TITLE
Moderne Ingest fails with SSL Handshake errors on Spring Petclinic and Markdown Generator (and maybe others)

### ISSUE THREAD

**Issue by mike-solomon** [openrewrite/rewrite-recipe-markdown-generator#20]
Related thread: https://moderneinc.slack.com/archives/C01VADFPJQZ/p1668467715650789

**Comment by traceyyoshima** [comment]
Hi @mike-solomon, I'm going to close this issue. I've remove the github moderne-ingest from both petclinic and markdown generator.

Context:
We used to have an ingest project that used those GH actions to produce ASTs, but that is no longer the case.
