### ISSUE TITLE
Run creates empty general section

### ISSUE THREAD

**Issue by mike-solomon** [openrewrite/rewrite-recipe-markdown-generator#32]
When I ran the markdown generator with `latest.release`, I noticed that in the `SUMMARY_snippet.md` file in the `build/docs/reference` directory that there is no `General` section. Instead, there's a section that looks like: 

```
  * [](reference/recipes//README.md)
    * [Delete files](/reference/recipes/deletesourcefiles.md)
    * [Find files](/reference/recipes/findsourcefiles.md)
    * [Find instances of type Quark](/reference/recipes/findquarks.md)
    * [Find source files with ParseExceptionResult markers](/reference/recipes/findparsefailures.md)
    * [Rename a file](/reference/recipes/renamefile.md)
    * [Set File Permission Attributes](/reference/recipes/setfilepermissions.md)
```

~In order to get these links to work appropriately, I had to manually update the [general section](https://github.com/openrewrite/rewrite-docs/blame/master/SUMMARY.md#L48-L54) of `rewrite-docs` and change the links to be in the appropriate format.~

Even manually updating the links does not fix the issue due to the way our docs are structured. These docs would need to be moved to a separate directory of some sort as the base directory doesn't allow for docs for whatever reason. 

We should make sure that the markdown generator is creating the appropriate summary snippet.

**Comment by mike-solomon** [comment]
Slack thread discussing this issue: https://moderneinc.slack.com/archives/C01VADFPJQZ/p1669756621584369

Looks like [Category Tree](https://github.com/openrewrite/rewrite/blob/bcfe59b7440b0d07ba88b50c7608432aad185c91/rewrite-core/src/main/java/org/openrewrite/config/CategoryTree.java#L37) needs to be added to this generator for that to work correctly.

**Comment by tkvangorder** [comment]
Closing this issue, as it appears fixed

**Comment by mike-solomon** [comment]
Re-opening - this is not fixed. Sam and I looked into it and it's much more complicated than original expected.
