### ISSUE TITLE
Add rewrite-static-analysis for 8.0

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-recipe-markdown-generator#54]
As part of 8.0 we're splitting off [openrewrite/rewrite-static-analysis](https://github.com/openrewrite/rewrite-static-analysis) into a separate project. This means we'll have to update the docs accordingly:

- [x] Add a dependency in `build.gradle.kts` on `rewrite-static-analysis` (RSA)
- [x] Ensure Maven/Gradle snippets for RSA recipes contain the correct dependency
- [x] Ensure RSA recipes link to the correct sources on GitHub

**Comment by mike-solomon** [comment]
@timtebeek I see that static analysis has been added to the `build.gradle.kts` file. Are the other parts of this done? Or do we still need to do something for those?

**Comment by mike-solomon** [comment]
I haven't copied over the generated recipes to `rewrite-docs`, yet so that makes sense. I'm planning on doing that with in coordination with the changelog going out: https://github.com/openrewrite/rewrite-docs/pull/176

**Comment by timtebeek** [comment]
OK great; I've checked the remaining two items and will assume you handle the deployment separately, thanks!
