### ISSUE TITLE
Add GitHub icon to GitHub link

### ISSUE THREAD

**Issue by mike-solomon** [openrewrite/rewrite-recipe-markdown-generator#82]
People are missing the link to the GitHub source for recipes. It was [suggested that we add the GitHub icon in front of the link to draw people's attention to that](https://github.com/openrewrite/rewrite-gradle-plugin/issues/243). 

Making an issue to track that.

**Comment by vlsi** [comment]
It would be better if a corresponding text could be added as well. For example: "if you need to customize the set of rules, you might copy the rule sources from ..."

A nice side-effect would be fixing the set of rules, so they would not accidentally change as users upgrade openrewrite

**Comment by mike-solomon** [comment]
I updated the title and added a note about the recipe sources. I think this fixes the issue. I didn't see an easy way to add the icon but I think that's less important with the other two changes.

![image](https://github.com/openrewrite/rewrite-recipe-markdown-generator/assets/1187834/ae1950e1-9a67-4e5c-92b5-cd84c879aed1)

Resolving.
